# Create cron job to automatically delete .mininet_history
---
- name: Setup mininet VM
  hosts: mininet
  tasks:

    - name: Install packages
      become: yes
      apt:
        update_cache: yes
        pkg:
          - x11-apps
          - vim
          - wireshark
          - wireshark-gtk
          - openvswitch-switch
          - iperf
          - curl
          - hping3
          - apache2-utils
          - python3-ryu
          - mininet
          - xterm
          - python3-tk
          - python3-pip
          - git
    - name: Configure X11 forwarding
      copy:
        src: files/x11.sh
        dest: ~/x11.sh
    - name: Append to the shell file
      shell: cat x11.sh >> .bashrc
    - name: Remove the shell file
      shell: rm x11.sh
    - name: Clone the mininet repository
      git:
        clone: yes
        repo: git://github.com/mininet/mininet
        dest: '/home/{{ansible_user}}/mininet'
    - name: Install setuptools
      pip:
        name:
          - setuptools
        executable: pip3
    - name: Install mininet
      become: yes
      command:
        chdir: '/home/{{ansible_user}}/mininet'
        cmd: python3 setup.py install
    - name: Copy lab 1 file
      copy:
        src: files/lab1.py
        dest: ~/mininet/examples/lab1.py
        mode: 0775
    - name: Copy lab 2 file
      copy:
        src: files/lab2.py
        dest: ~/mininet/examples/lab2.py
        mode: 0775
    - name: Copy lab 3 file
      copy:
        src: files/lab3.py
        dest: ~/mininet/examples/lab3.py
        mode: 0775
    - name: Allow wireshark to work for sudoers
      command: echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections

